                                                                                                            def                                                                                                             
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CREATE OR REPLACE FUNCTION public.auto_approve_if_matches_latest_validated_shift()                                                                                                                                        +
  RETURNS trigger                                                                                                                                                                                                          +
  LANGUAGE plpgsql                                                                                                                                                                                                         +
  SECURITY DEFINER                                                                                                                                                                                                         +
 AS $function$DECLARE\r                                                                                                                                                                                                    +
 v_current_count       int;\r                                                                                                                                                                                              +
 v_current_heure_debut time;\r                                                                                                                                                                                             +
 v_current_heure_fin   time;\r                                                                                                                                                                                             +
 v_current_panier      boolean;\r                                                                                                                                                                                          +
 v_current_deplacement boolean;\r                                                                                                                                                                                          +
 \r                                                                                                                                                                                                                        +
 v_prev_chantier       uuid;\r                                                                                                                                                                                             +
 v_prev_heure_debut    time;\r                                                                                                                                                                                             +
 v_prev_heure_fin      time;\r                                                                                                                                                                                             +
 v_prev_panier         boolean;\r                                                                                                                                                                                          +
 v_prev_deplacement    boolean;\r                                                                                                                                                                                          +
 BEGIN\r                                                                                                                                                                                                                   +
 -- Only evaluate pending declarations.\r                                                                                                                                                                                  +
 IF NEW.statut <> 'soumise' THEN\r                                                                                                                                                                                         +
 RETURN NEW;\r                                                                                                                                                                                                             +
 END IF;\r                                                                                                                                                                                                                 +
 \r                                                                                                                                                                                                                        +
 -- Current declaration must represent exactly one active period with valid times.\r                                                                                                                                       +
 SELECT\r                                                                                                                                                                                                                  +
 COUNT(*),\r                                                                                                                                                                                                               +
 MIN(p.heure_debut),\r                                                                                                                                                                                                     +
 MIN(p.heure_fin),\r                                                                                                                                                                                                       +
 BOOL_AND(COALESCE(p.panier_repas, false)),\r                                                                                                                                                                              +
 BOOL_AND(COALESCE(p.deplacement, false))\r                                                                                                                                                                                +
 INTO\r                                                                                                                                                                                                                    +
 v_current_count,\r                                                                                                                                                                                                        +
 v_current_heure_debut,\r                                                                                                                                                                                                  +
 v_current_heure_fin,\r                                                                                                                                                                                                    +
 v_current_panier,\r                                                                                                                                                                                                       +
 v_current_deplacement\r                                                                                                                                                                                                   +
 FROM public.periodes_travail p\r                                                                                                                                                                                          +
 WHERE p.user_id    = NEW.user_id\r                                                                                                                                                                                        +
 AND p.chantier_id = NEW.chantier_id\r                                                                                                                                                                                     +
 AND p.date        = NEW.date\r                                                                                                                                                                                            +
 AND p.statut     <> 'rejetee';\r                                                                                                                                                                                          +
 \r                                                                                                                                                                                                                        +
 IF v_current_count <> 1 OR v_current_heure_debut IS NULL OR v_current_heure_fin IS NULL THEN\r                                                                                                                            +
 RETURN NEW;\r                                                                                                                                                                                                             +
 END IF;\r                                                                                                                                                                                                                 +
 \r                                                                                                                                                                                                                        +
 -- Find the worker's most recent previously validated period\r                                                                                                                                                            +
 -- (strictly before this date, or same date but different shift).\r                                                                                                                                                       +
 SELECT\r                                                                                                                                                                                                                  +
 p.chantier_id,\r                                                                                                                                                                                                          +
 p.heure_debut,\r                                                                                                                                                                                                          +
 p.heure_fin,\r                                                                                                                                                                                                            +
 COALESCE(p.panier_repas, false),\r                                                                                                                                                                                        +
 COALESCE(p.deplacement, false)\r                                                                                                                                                                                          +
 INTO\r                                                                                                                                                                                                                    +
 v_prev_chantier,\r                                                                                                                                                                                                        +
 v_prev_heure_debut,\r                                                                                                                                                                                                     +
 v_prev_heure_fin,\r                                                                                                                                                                                                       +
 v_prev_panier,\r                                                                                                                                                                                                          +
 v_prev_deplacement\r                                                                                                                                                                                                      +
 FROM public.periodes_travail p\r                                                                                                                                                                                          +
 WHERE p.user_id = NEW.user_id\r                                                                                                                                                                                           +
 AND p.statut  = 'validee'\r                                                                                                                                                                                               +
 AND (\r                                                                                                                                                                                                                   +
 p.date < NEW.date\r                                                                                                                                                                                                       +
 OR (p.date = NEW.date AND (p.chantier_id <> NEW.chantier_id OR p.heure_debut <> v_current_heure_debut))\r                                                                                                                 +
 )\r                                                                                                                                                                                                                       +
 ORDER BY p.date DESC, p.heure_debut DESC\r                                                                                                                                                                                +
 LIMIT 1;\r                                                                                                                                                                                                                +
 \r                                                                                                                                                                                                                        +
 -- No prior validated shift — cannot auto-approve.\r                                                                                                                                                                      +
 IF v_prev_chantier IS NULL THEN\r                                                                                                                                                                                         +
 RETURN NEW;\r                                                                                                                                                                                                             +
 END IF;\r                                                                                                                                                                                                                 +
 \r                                                                                                                                                                                                                        +
 -- Exact match required: same worksite, same hours, same allowances.\r                                                                                                                                                    +
 IF v_prev_chantier       = NEW.chantier_id\r                                                                                                                                                                              +
 AND v_prev_heure_debut = v_current_heure_debut\r                                                                                                                                                                          +
 AND v_prev_heure_fin   = v_current_heure_fin\r                                                                                                                                                                            +
 AND v_prev_panier      = COALESCE(v_current_panier, false)\r                                                                                                                                                              +
 AND v_prev_deplacement = COALESCE(v_current_deplacement, false) THEN\r                                                                                                                                                    +
 \r                                                                                                                                                                                                                        +
 UPDATE public.declarations_heures\r                                                                                                                                                                                       +
 SET\r                                                                                                                                                                                                                     +
 statut       = 'validee',\r                                                                                                                                                                                               +
 validated_at = NOW(),\r                                                                                                                                                                                                   +
 updated_at   = NOW()\r                                                                                                                                                                                                    +
 WHERE id     = NEW.id\r                                                                                                                                                                                                   +
 AND statut = 'soumise';\r                                                                                                                                                                                                 +
 \r                                                                                                                                                                                                                        +
 END IF;\r                                                                                                                                                                                                                 +
 \r                                                                                                                                                                                                                        +
 RETURN NEW;\r                                                                                                                                                                                                             +
 END;$function$                                                                                                                                                                                                            +
 
 CREATE OR REPLACE FUNCTION public.calculer_duree_periode(heure_debut time without time zone, heure_fin time without time zone)                                                                                            +
  RETURNS numeric                                                                                                                                                                                                          +
  LANGUAGE plpgsql                                                                                                                                                                                                         +
  IMMUTABLE                                                                                                                                                                                                                +
 AS $function$\r                                                                                                                                                                                                           +
 BEGIN\r                                                                                                                                                                                                                   +
   IF heure_fin IS NULL THEN\r                                                                                                                                                                                             +
     RETURN 0;\r                                                                                                                                                                                                           +
   END IF;\r                                                                                                                                                                                                               +
   \r                                                                                                                                                                                                                      +
   -- Calcul de la différence en heures (avec décimales)\r                                                                                                                                                                 +
   RETURN EXTRACT(EPOCH FROM (heure_fin - heure_debut)) / 3600.0;\r                                                                                                                                                        +
 END;\r                                                                                                                                                                                                                    +
 $function$                                                                                                                                                                                                                +
 
 CREATE OR REPLACE FUNCTION public.delete_chantier_cascade(p_chantier_id uuid)                                                                                                                                             +
  RETURNS void                                                                                                                                                                                                             +
  LANGUAGE plpgsql                                                                                                                                                                                                         +
  SECURITY DEFINER                                                                                                                                                                                                         +
 AS $function$BEGIN\r                                                                                                                                                                                                      +
 -- Verify caller is admin\r                                                                                                                                                                                               +
 IF (SELECT role FROM profiles WHERE id = auth.uid()) != 'admin' THEN\r                                                                                                                                                    +
 RAISE EXCEPTION 'Accès refusé';\r                                                                                                                                                                                         +
 END IF;\r                                                                                                                                                                                                                 +
 \r                                                                                                                                                                                                                        +
 DELETE FROM zones_chantiers WHERE chantier_id = p_chantier_id;\r                                                                                                                                                          +
 DELETE FROM affectations_chantiers WHERE chantier_id = p_chantier_id;\r                                                                                                                                                   +
 DELETE FROM periodes_travail WHERE chantier_id = p_chantier_id;\r                                                                                                                                                         +
 DELETE FROM declarations_heures WHERE chantier_id = p_chantier_id;\r                                                                                                                                                      +
 DELETE FROM chantiers WHERE id = p_chantier_id;\r                                                                                                                                                                         +
 END;$function$                                                                                                                                                                                                            +
 
 CREATE OR REPLACE FUNCTION public.get_chef_chantier_ids(chef_id uuid)                                                                                                                                                     +
  RETURNS TABLE(chantier_id uuid)                                                                                                                                                                                          +
  LANGUAGE plpgsql                                                                                                                                                                                                         +
  SECURITY DEFINER                                                                                                                                                                                                         +
 AS $function$\r                                                                                                                                                                                                           +
 BEGIN\r                                                                                                                                                                                                                   +
   RETURN QUERY\r                                                                                                                                                                                                          +
   SELECT DISTINCT ac.chantier_id\r                                                                                                                                                                                        +
   FROM public.affectations_chantiers ac\r                                                                                                                                                                                 +
   WHERE ac.user_id = chef_id\r                                                                                                                                                                                            +
     AND ac.date_fin IS NULL;\r                                                                                                                                                                                            +
 END;\r                                                                                                                                                                                                                    +
 $function$                                                                                                                                                                                                                +
 
 CREATE OR REPLACE FUNCTION public.get_my_role()                                                                                                                                                                           +
  RETURNS text                                                                                                                                                                                                             +
  LANGUAGE sql                                                                                                                                                                                                             +
  SECURITY DEFINER                                                                                                                                                                                                         +
 AS $function$SELECT role FROM public.profiles WHERE id = auth.uid();$function$                                                                                                                                            +
 
 CREATE OR REPLACE FUNCTION public.is_admin()                                                                                                                                                                              +
  RETURNS boolean                                                                                                                                                                                                          +
  LANGUAGE sql                                                                                                                                                                                                             +
  SECURITY DEFINER                                                                                                                                                                                                         +
 AS $function$SELECT EXISTS (\r                                                                                                                                                                                            +
 SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'\r                                                                                                                                                         +
 );$function$                                                                                                                                                                                                              +
 
 CREATE OR REPLACE FUNCTION public.is_zone_owner(p_zone_id uuid)                                                                                                                                                           +
  RETURNS boolean                                                                                                                                                                                                          +
  LANGUAGE sql                                                                                                                                                                                                             +
  SECURITY DEFINER                                                                                                                                                                                                         +
 AS $function$SELECT EXISTS (\r                                                                                                                                                                                            +
 SELECT 1 FROM zones_equipe\r                                                                                                                                                                                              +
 WHERE id = p_zone_id\r                                                                                                                                                                                                    +
 AND chef_equipe_id = auth.uid()\r                                                                                                                                                                                         +
 );$function$                                                                                                                                                                                                              +
 
 CREATE OR REPLACE FUNCTION public.rls_auto_enable()                                                                                                                                                                       +
  RETURNS event_trigger                                                                                                                                                                                                    +
  LANGUAGE plpgsql                                                                                                                                                                                                         +
  SECURITY DEFINER                                                                                                                                                                                                         +
  SET search_path TO 'pg_catalog'                                                                                                                                                                                          +
 AS $function$                                                                                                                                                                                                             +
 DECLARE                                                                                                                                                                                                                   +
   cmd record;                                                                                                                                                                                                             +
 BEGIN                                                                                                                                                                                                                     +
   FOR cmd IN                                                                                                                                                                                                              +
     SELECT *                                                                                                                                                                                                              +
     FROM pg_event_trigger_ddl_commands()                                                                                                                                                                                  +
     WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')                                                                                                                                               +
       AND object_type IN ('table','partitioned table')                                                                                                                                                                    +
   LOOP                                                                                                                                                                                                                    +
      IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN+
       BEGIN                                                                                                                                                                                                               +
         EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);                                                                                                                        +
         RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;                                                                                                                                               +
       EXCEPTION                                                                                                                                                                                                           +
         WHEN OTHERS THEN                                                                                                                                                                                                  +
           RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;                                                                                                                                    +
       END;                                                                                                                                                                                                                +
      ELSE                                                                                                                                                                                                                 +
         RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;                                                                                     +
      END IF;                                                                                                                                                                                                              +
   END LOOP;                                                                                                                                                                                                               +
 END;                                                                                                                                                                                                                      +
 $function$                                                                                                                                                                                                                +
 
 CREATE OR REPLACE FUNCTION public.sync_declarations_from_periods()                                                                                                                                                        +
  RETURNS trigger                                                                                                                                                                                                          +
  LANGUAGE plpgsql                                                                                                                                                                                                         +
  SECURITY DEFINER                                                                                                                                                                                                         +
 AS $function$DECLARE\r                                                                                                                                                                                                    +
 v_user_id    uuid;\r                                                                                                                                                                                                      +
 v_chantier   uuid;\r                                                                                                                                                                                                      +
 v_date       date;\r                                                                                                                                                                                                      +
 v_count      int;\r                                                                                                                                                                                                       +
 BEGIN\r                                                                                                                                                                                                                   +
 v_user_id  := COALESCE(NEW.user_id,    OLD.user_id);\r                                                                                                                                                                    +
 v_chantier := COALESCE(NEW.chantier_id, OLD.chantier_id);\r                                                                                                                                                               +
 v_date     := COALESCE(NEW.date,        OLD.date);\r                                                                                                                                                                      +
 \r                                                                                                                                                                                                                        +
 SELECT COUNT(*) INTO v_count\r                                                                                                                                                                                            +
 FROM periodes_travail\r                                                                                                                                                                                                   +
 WHERE user_id    = v_user_id\r                                                                                                                                                                                            +
 AND chantier_id = v_chantier\r                                                                                                                                                                                            +
 AND date        = v_date\r                                                                                                                                                                                                +
 AND statut     != 'rejetee';\r                                                                                                                                                                                            +
 \r                                                                                                                                                                                                                        +
 IF v_count = 0 THEN\r                                                                                                                                                                                                     +
 DELETE FROM declarations_heures\r                                                                                                                                                                                         +
 WHERE user_id    = v_user_id\r                                                                                                                                                                                            +
 AND chantier_id = v_chantier\r                                                                                                                                                                                            +
 AND date        = v_date;\r                                                                                                                                                                                               +
 ELSE\r                                                                                                                                                                                                                    +
 INSERT INTO declarations_heures (\r                                                                                                                                                                                       +
 user_id,\r                                                                                                                                                                                                                +
 chantier_id,\r                                                                                                                                                                                                            +
 date,\r                                                                                                                                                                                                                   +
 heures_normales,\r                                                                                                                                                                                                        +
 heures_supplementaires,\r                                                                                                                                                                                                 +
 nb_paniers,\r                                                                                                                                                                                                             +
 statut,\r                                                                                                                                                                                                                 +
 from_suggestion,\r                                                                                                                                                                                                        +
 updated_at\r                                                                                                                                                                                                              +
 )\r                                                                                                                                                                                                                       +
 SELECT\r                                                                                                                                                                                                                  +
 s.user_id,\r                                                                                                                                                                                                              +
 s.chantier_id,\r                                                                                                                                                                                                          +
 s.date,\r                                                                                                                                                                                                                 +
 s.heures_normales,\r                                                                                                                                                                                                      +
 s.heures_supplementaires,\r                                                                                                                                                                                               +
 s.nb_paniers,\r                                                                                                                                                                                                           +
 s.statut,\r                                                                                                                                                                                                               +
 -- true if any active period in this group came from a suggestion\r                                                                                                                                                       +
 EXISTS (\r                                                                                                                                                                                                                +
 SELECT 1 FROM periodes_travail p2\r                                                                                                                                                                                       +
 WHERE p2.user_id    = v_user_id\r                                                                                                                                                                                         +
 AND p2.chantier_id = v_chantier\r                                                                                                                                                                                         +
 AND p2.date        = v_date\r                                                                                                                                                                                             +
 AND p2.from_suggestion = true\r                                                                                                                                                                                           +
 AND p2.statut     != 'rejetee'\r                                                                                                                                                                                          +
 ),\r                                                                                                                                                                                                                      +
 NOW()\r                                                                                                                                                                                                                   +
 FROM synthese_heures_journalieres s\r                                                                                                                                                                                     +
 WHERE s.user_id    = v_user_id\r                                                                                                                                                                                          +
 AND s.chantier_id = v_chantier\r                                                                                                                                                                                          +
 AND s.date        = v_date\r                                                                                                                                                                                              +
 ON CONFLICT (user_id, chantier_id, date)\r                                                                                                                                                                                +
 DO UPDATE SET\r                                                                                                                                                                                                           +
 heures_normales        = EXCLUDED.heures_normales,\r                                                                                                                                                                      +
 heures_supplementaires = EXCLUDED.heures_supplementaires,\r                                                                                                                                                               +
 nb_paniers             = EXCLUDED.nb_paniers,\r                                                                                                                                                                           +
 statut                 = EXCLUDED.statut,\r                                                                                                                                                                               +
 from_suggestion        = EXCLUDED.from_suggestion,\r                                                                                                                                                                      +
 updated_at             = NOW();\r                                                                                                                                                                                         +
 END IF;\r                                                                                                                                                                                                                 +
 \r                                                                                                                                                                                                                        +
 RETURN COALESCE(NEW, OLD);\r                                                                                                                                                                                              +
 END;$function$                                                                                                                                                                                                            +
 
 CREATE OR REPLACE FUNCTION public.sync_periods_from_declaration()                                                                                                                                                         +
  RETURNS trigger                                                                                                                                                                                                          +
  LANGUAGE plpgsql                                                                                                                                                                                                         +
  SECURITY DEFINER                                                                                                                                                                                                         +
 AS $function$BEGIN\r                                                                                                                                                                                                      +
 IF NEW.statut IN ('validee', 'rejetee')\r                                                                                                                                                                                 +
 AND (OLD.statut IS NULL OR OLD.statut IS DISTINCT FROM NEW.statut) THEN\r                                                                                                                                                 +
 UPDATE periodes_travail\r                                                                                                                                                                                                 +
 SET\r                                                                                                                                                                                                                     +
 statut       = NEW.statut,\r                                                                                                                                                                                              +
 validated_by = NEW.validated_by,\r                                                                                                                                                                                        +
 validated_at = NEW.validated_at,\r                                                                                                                                                                                        +
 updated_at   = NOW()\r                                                                                                                                                                                                    +
 WHERE user_id    = NEW.user_id\r                                                                                                                                                                                          +
 AND chantier_id = NEW.chantier_id\r                                                                                                                                                                                       +
 AND date        = NEW.date\r                                                                                                                                                                                              +
 AND statut IN ('terminee', 'en_cours');\r                                                                                                                                                                                 +
 END IF;\r                                                                                                                                                                                                                 +
 RETURN NEW;\r                                                                                                                                                                                                             +
 END;$function$                                                                                                                                                                                                            +
 
(10 rows)

